Issue #7: Prevent PHP warning when parsing render array.
mortenson/psalm-plugin-drupal pull request #8
Opened 2022-12-27 16:38 UTC by FlorentTorregrosa

Note that as I don't know Psalm, I only fix the symptom.

There may be a bigger problem.

2022-12-27 16:40 UTC, FlorentTorregrosa commented
Attaching patch file for easier Composer usage.
[psalm-plugin-drupal-8.patch.txt](https://github.com/mortenson/psalm-plugin-drupal/files/10309654/psalm-plugin-drupal-8.patch.txt)

2022-12-27 18:03 UTC, mortenson requested changes
Thanks! I'm away from my main computer but PHPCS caught that this line is a bit too long now. Could you break these into newlines?

2022-12-28 11:43 UTC, FlorentTorregrosa commented
Hi,

No problem. Done :)

2022-12-29 18:51 UTC, mortenson approved these changes

2022-12-29 18:51 UTC, merged